//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab12_WPF.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Spocti", ReplyAction="http://tempuri.org/IService1/SpoctiResponse")]
        decimal Spocti(decimal operand1, decimal operand2, string operace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Spocti", ReplyAction="http://tempuri.org/IService1/SpoctiResponse")]
        System.Threading.Tasks.Task<decimal> SpoctiAsync(decimal operand1, decimal operand2, string operace);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Lab12_WPF.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Lab12_WPF.ServiceReference1.IService1>, Lab12_WPF.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal Spocti(decimal operand1, decimal operand2, string operace) {
            return base.Channel.Spocti(operand1, operand2, operace);
        }
        
        public System.Threading.Tasks.Task<decimal> SpoctiAsync(decimal operand1, decimal operand2, string operace) {
            return base.Channel.SpoctiAsync(operand1, operand2, operace);
        }
    }
}
